name: Testing

on:
    pull_request:
            branches:
                - mainline

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Installing Yarn
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
            - name: Installing dependencies
              run: yarn
            - name: Linting the code
              run: yarn lint
            - name: Building the code
              run: yarn build
